//! Parity with the Python reference implementation (harness-router `nav2_format.py`, `nav2.py`,
//! `where_next.py`). `golden/sources.json` was generated by running that reference over the files in
//! `fixtures/src`; every field here must match it exactly.

use std::path::Path;

use serde::Deserialize;
use wn_sources::{
    config_doc, file_doc, first_comment, function_docs, is_source, kind_of, lang_of, read_text,
    skeleton, symbols, Kind,
};

#[derive(Deserialize)]
struct Golden {
    files: Vec<GoldenFile>,
    paths: Vec<GoldenPath>,
}

#[derive(Deserialize)]
struct GoldenSymbol {
    name: String,
    line: usize,
    end: usize,
}

#[derive(Deserialize)]
struct GoldenFile {
    path: String,
    lang: Option<String>,
    is_source: bool,
    kind: Option<String>,
    first_comment: Option<String>,
    symbols: Vec<GoldenSymbol>,
    skeleton: String,
    file_doc: String,
    function_docs: Vec<(String, usize, String)>,
    config_doc: String,
}

#[derive(Deserialize)]
struct GoldenPath {
    path: String,
    lang: Option<String>,
    is_source: bool,
    kind: Option<String>,
}

fn golden() -> Golden {
    let raw = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/sources.json"),
    )
    .unwrap();
    serde_json::from_str(&raw).unwrap()
}

fn kind_name(kind: Option<Kind>) -> Option<String> {
    kind.map(|k| k.as_str().to_string())
}

#[test]
fn file_outputs_match_reference() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/src");
    let g = golden();
    assert!(g.files.len() >= 15);
    for f in &g.files {
        let text = read_text(&dir.join(&f.path), 400_000).unwrap();
        let p = f.path.as_str();
        assert_eq!(lang_of(p).map(str::to_string), f.lang, "lang {p}");
        assert_eq!(is_source(p), f.is_source, "is_source {p}");
        assert_eq!(kind_name(kind_of(p)), f.kind, "kind {p}");
        assert_eq!(first_comment(&text), f.first_comment, "first_comment {p}");
        let syms = symbols(p, &text);
        let got: Vec<(String, usize, usize)> = syms
            .iter()
            .map(|s| (s.name.clone(), s.line, s.end))
            .collect();
        let want: Vec<(String, usize, usize)> = f
            .symbols
            .iter()
            .map(|s| (s.name.clone(), s.line, s.end))
            .collect();
        assert_eq!(got, want, "symbols {p}");
        assert_eq!(skeleton(p, &text, 1500), f.skeleton, "skeleton {p}");
        assert_eq!(file_doc(p, &text), f.file_doc, "file_doc {p}");
        assert_eq!(
            function_docs(p, &text),
            f.function_docs,
            "function_docs {p}"
        );
        assert_eq!(config_doc(p, &text, 15), f.config_doc, "config_doc {p}");
    }
}

#[test]
fn path_classification_matches_reference() {
    for case in golden().paths {
        let p = case.path.as_str();
        assert_eq!(lang_of(p).map(str::to_string), case.lang, "lang {p}");
        assert_eq!(is_source(p), case.is_source, "is_source {p}");
        assert_eq!(kind_name(kind_of(p)), case.kind, "kind {p}");
    }
}
