//! Parity with the Python reference implementation (harness-router `where_next.py`, `nav2.py`,
//! `contextbench.py`). `golden/core.json` was generated by running that reference; the adapter
//! fixtures are random unit vectors with the negatives the reference sampled.

use std::path::Path;

use serde::Deserialize;
use serde_json::Value;
use wn_core::adapter::{apply_adapter, fit_adapter, revision, AdapterParams};
use wn_core::rank::{abstain_reason, budget, render, rrf, Hint, Hints, Outcome};
use wn_core::text::{history_query, query_text, Granularity};

#[derive(Deserialize)]
struct Golden {
    adapter: Vec<AdapterCase>,
    abstain: Vec<AbstainCase>,
    budget: Vec<BudgetCase>,
    render: Vec<RenderCase>,
    queries: Vec<QueryCase>,
    history: Vec<HistoryCase>,
    rrf: Vec<RrfCase>,
}

#[derive(Deserialize)]
struct AdapterCase {
    qv: Vec<Vec<f32>>,
    cand: Vec<Vec<f32>>,
    pos: Vec<usize>,
    negs: Vec<Vec<usize>>,
    #[serde(rename = "W")]
    w: Vec<Vec<f32>>,
    probe: Vec<f32>,
    applied: Vec<f32>,
    #[serde(rename = "W_f16_revision")]
    revision: String,
}

#[derive(Deserialize)]
struct AbstainCase {
    files: Vec<Hint>,
    adapted: bool,
    strict: bool,
    fallback: bool,
    reason: Option<String>,
}

#[derive(Deserialize)]
struct BudgetCase {
    input: Hints,
    output: Hints,
}

#[derive(Deserialize)]
struct RenderCase {
    out: Value,
    text: String,
}

#[derive(Deserialize)]
struct QueryCase {
    query: String,
    context: Option<String>,
    granularity: String,
    text: String,
}

#[derive(Deserialize)]
struct HistoryCase {
    subject: String,
    body: String,
    text: String,
}

#[derive(Deserialize)]
struct RrfCase {
    orders: Vec<Vec<usize>>,
    fused: Vec<usize>,
}

fn golden() -> Golden {
    let raw = std::fs::read_to_string(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/core.json"),
    )
    .unwrap();
    serde_json::from_str(&raw).unwrap()
}

fn flat(rows: &[Vec<f32>]) -> Vec<f32> {
    rows.iter().flatten().copied().collect()
}

#[test]
fn adapter_fit_matches_reference() {
    for (i, case) in golden().adapter.iter().enumerate() {
        let d = case.qv[0].len();
        let w = fit_adapter(
            &flat(&case.qv),
            &flat(&case.cand),
            d,
            &case.pos,
            &case.negs,
            &AdapterParams::default(),
        );
        let want = flat(&case.w);
        let max_err = w
            .iter()
            .zip(&want)
            .map(|(a, b)| (a - b).abs())
            .fold(0.0f32, f32::max);
        // Measured: ~1e-7 (float rounding) while W moves ~0.1 away from the identity.
        assert!(max_err < 1e-5, "case {i}: max |W - W_ref| = {max_err}");
        let applied = apply_adapter(&case.probe, &w, d);
        for (a, b) in applied.iter().zip(&case.applied) {
            assert!((a - b).abs() < 1e-5, "case {i}: applied {a} vs {b}");
        }
        // Revisions hash the float16 weights, so tiny float differences rarely change them; the
        // reference weights must hash identically.
        assert_eq!(revision(&want), case.revision, "case {i} revision");
    }
}

#[test]
fn abstain_matches_reference() {
    for (i, c) in golden().abstain.iter().enumerate() {
        assert_eq!(
            abstain_reason(&c.files, c.adapted, c.strict, c.fallback),
            c.reason,
            "case {i}"
        );
    }
}

#[test]
fn budget_matches_reference() {
    for (i, c) in golden().budget.into_iter().enumerate() {
        assert_eq!(budget(c.input), c.output, "case {i}");
    }
}

#[test]
fn render_matches_reference() {
    for c in golden().render {
        let out: Outcome = serde_json::from_value(c.out).unwrap();
        assert_eq!(render(&out), c.text);
    }
}

#[test]
fn query_text_matches_reference() {
    for c in golden().queries {
        let g = match c.granularity.as_str() {
            "function" => Granularity::Function,
            _ => Granularity::File,
        };
        assert_eq!(
            query_text(&c.query, c.context.as_deref().unwrap_or(""), g),
            c.text
        );
    }
}

#[test]
fn history_query_matches_reference() {
    for c in golden().history {
        assert_eq!(history_query(&c.subject, &c.body), c.text);
    }
}

#[test]
fn rrf_matches_reference() {
    for c in golden().rrf {
        let orders: Vec<&[usize]> = c.orders.iter().map(Vec::as_slice).collect();
        assert_eq!(rrf(&orders, 60), c.fused);
    }
}

#[test]
fn history_query_is_query_text_of_history_body() {
    use wn_core::text::history_body;
    for c in golden().history {
        assert_eq!(
            query_text(&history_body(&c.subject, &c.body), "", Granularity::File),
            c.text
        );
    }
}
