[package]
name = "wn-cli"
description = "The `wn` command"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "wn_cli"
path = "src/lib.rs"

[[bin]]
name = "wn"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha1_smol = "1"
wn-core.workspace = true
wn-git = { path = "../wn-git" }
wn-sources = { path = "../wn-sources" }

[dev-dependencies]
insta = { version = "1.48", features = ["filters"] }
tempfile = "3"

[lints]
workspace = true
